# Config the cactus theme
theme_config:
  colorscheme: white

nav:
  Home: /
  Articles: /archives/
  Tags: /tags/
  Search: /search/

copyright:
  start_year: 2017
  end_year:

posts_overview:
  show_all_posts: false
  post_count: 10
  sort_updated: false

social_links: false

logo:
  enabled: true
  width: 50
  height: 50
  url: /uploads/avatar.png
  gravatar: false


reading_progress:
  enable: true
  # Available values: left | right
  start_at: left
  # Available values: top | bottom
  position: top
  reversed: true
  color: "#37c6c0"
  height: 2px