# Allow to cache content generation.
cache:
  enable: true

# Remove unnecessary files after hexo generate.
minify: true

#scheme: Muse
scheme: Mist
#scheme: Pisces
#scheme: Gemini


darkmode: true

creative_commons:
  # Available values: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | cc-zero
  license: by-nc-sa
  # Available values: big | small
  size: big
  sidebar: true
  post: false
  language: deed.en

menu:
  home: / || fa fa-home
  #about: /about/ || fa fa-user
  #categories: /categories/ || fa fa-th
  Articles: /archives/ || fa fa-archive
  Tags: /tags/ || fa fa-tags
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

menu_settings:
  icons: true

avatar:
  url: /uploads/avatar.jpg
  rounded: true


footer:
  since: 2017
  icon:
    animated: false

# Multiple Comment System Support
comments:
  # Available values: tabs | buttons
  style: tabs
  # Choose a comment system to be displayed by default
  # Available values: disqus | disqusjs | changyan | livere | gitalk | utterances | isso
  active: utterances
  # Setting `true` means remembering the comment system selected by the visitor
  storage: true
  # Lazyload all comment systems.
  lazyload: true
  # Modify icons and texts for any style, here are some examples
  nav:
    #disqus:
    #  text: Load Disqus
    #  order: -1
    #gitalk:
    #  order: -2

reading_progress:
  enable: true
  # Available values: left | right
  start_at: left
  # Available values: top | bottom
  position: top
  reversed: false
  color: "#37c6c0"
  height: 2px

symbols_count_time:
  separated_meta: false
  item_text_total: false

# Local search
# Dependencies: https://github.com/next-theme/hexo-generator-searchdb
local_search:
  enable: true
  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  trigger: auto
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: false
  # Preload the search data when the page loads.
  preload: false

post_meta:
  updated_at:
    enable: false
    another_day: false
  categories: false

site_state: false

related_posts:
  enable: true


favicon:
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/logo.svg
  android_manifest: /images/site.webmanifest

sidebar:
  width: 280
  display: hide

text_align:
  # Available values: start | end | left | right | center | justify | justify-all | match-parent
  desktop: justify
  mobile: justify


google-site-verification: pJKZndHp7TM-q2rjTbI3HDmSxfwmS7p8F_TxH4WDXFA

  # Google Analytics
google_analytics:
  tracking_id: UA-53592781-1
  only_pageview: false

utterances:
  enable: true
  repo: kenmjlee/comment_repo # Github repository owner and name
  # Available values: pathname | url | title | og:title
  issue_term: pathname
  # Available values: github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light
  theme: preferred-color-scheme