name: Hexo Deployment CI

on:
  push:
    branches:
      - source
  watch:
    types: started

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    # Verify the sender
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node_version: [12.x]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: source
          submodules: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      # Caching dependencies to speed up workflows. (GitHub will remove any cache entries that have not been accessed in over 7 days.)
      - name: Cache node modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Pre-build
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name 'kenmjlee'
          git config --global user.email 'kenmjlee@users.noreply.github.com'
          npm i -g hexo-cli
          npm i
        #  git clone https://github.com:theme-next/hexo-theme-next --depth=1 themes/next
        # git clone git@github.com:theme-next/theme-next-three --depth=1 themes/next/source/lib/three
        # git clone git@github.com:theme-next/theme-next-reading-progress --depth=1 themes/next/source/lib/reading_progress
        # git clone git@github.com:theme-next/theme-next-pace --depth=1 themes/next/source/lib/pace      
        # git clone https://github.com/probberechts/hexo-theme-cactus.git themes/cactus
        
      - name: Build
        run: |
          hexo clean && hexo generate && hexo deploy
